#pragma once

#define TYPE_LIST                                                              \
    X(bool, 'b')                                                               \
    X(float, 'f')                                                              \
    X(int, 'i')

// X(opcode, supported)
#define OPCODE_LIST                                                            \
    X(add, 1)                                                                  \
    X(mul, 1)                                                                  \
    X(sub, 1)                                                                  \
    X(div, 1)                                                                  \
    X(eq, 1)                                                                   \
    X(lt, 1)                                                                   \
    X(gt, 1)                                                                   \
    X(le, 1)                                                                   \
    X(ge, 1)                                                                   \
    X(and, 1)                                                                  \
    X(or, 1)                                                                   \
    X(not, 1)                                                                  \
    X(jmp, 1)                                                                  \
    X(br, 1)                                                                   \
    X(call, 1)                                                                 \
    X(ret, 1)                                                                  \
    X(fadd, 1)                                                                 \
    X(fmul, 1)                                                                 \
    X(fsub, 1)                                                                 \
    X(fdiv, 1)                                                                 \
    X(feq, 1)                                                                  \
    X(flt, 1)                                                                  \
    X(fgt, 1)                                                                  \
    X(fle, 1)                                                                  \
    X(fge, 1)                                                                  \
    X(id, 1)                                                                   \
    X(const, 1)                                                                \
    X(print, 1)                                                                \
    X(label, 1)                                                                \
    X(nop, 0)                                                                  \
    X(set, 0)                                                                  \
    X(get, 0)                                                                  \
    X(alloc, 0)                                                                \
    X(free, 0)                                                                 \
    X(store, 0)                                                                \
    X(load, 0)                                                                 \
    X(ptradd, 0)                                                               \
    X(speculate, 0)                                                            \
    X(commit, 0)                                                               \
    X(guard, 0)                                                                \
    X(ceq, 0)                                                                  \
    X(clt, 0)                                                                  \
    X(cle, 0)                                                                  \
    X(cgt, 0)                                                                  \
    X(cge, 0)                                                                  \
    X(char2int, 0)                                                             \
    X(int2char, 0)                                                             \
    X(float2bits, 0)                                                           \
    X(bits2float, 0)                                                           \
    X(any, 0)
